# Generated by Django 4.1.5 on 2023-01-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unitCode', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('purchasePrice', models.IntegerField()),
                ('purchaseYear', models.CharField(max_length=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInventories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('maintenanceDate', models.CharField(max_length=11)),
                ('maintenanceVendor', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventories')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'db_table': 'maintenance_inventories',
            },
        ),
    ]
