# Generated by Django 4.1.5 on 2023-01-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_table'),
        ('inventory', '0002_alter_maintenanceinventories_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinventories',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_inventory', to='inventory.inventories'),
        ),
        migrations.AlterField(
            model_name='maintenanceinventories',
            name='maintenanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenanceinventories',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_staff', to='staff.staff'),
        ),
    ]
