# Generated by Django 4.1.5 on 2023-01-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staffs',
        ),
    ]
